//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.DisbursementLists = new HashSet<DisbursementList>();
            this.Employees = new HashSet<Employee>();
        }
    
        public string DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> ContactPersonId { get; set; }
        public Nullable<int> HeadId { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public Nullable<int> CollectionPointId { get; set; }
        public Nullable<int> RepresentativeId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual ICollection<DisbursementList> DisbursementLists { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual CollectionPoint CollectionPoint { get; set; }
    }
}
