//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisbursementListDetail
    {
        public int DisbursementListDetailId { get; set; }
        public int DisbursementListId { get; set; }
        public string StationeryId { get; set; }
        public int RequestQty { get; set; }
        public Nullable<int> ReceivedQty { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> GivenQty { get; set; }
    
        public virtual DisbursementList DisbursementList { get; set; }
        public virtual Stationery Stationery { get; set; }
    }
}
