//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisbursementList
    {
        public DisbursementList()
        {
            this.DisbursementListDetails = new HashSet<DisbursementListDetail>();
        }
    
        public int DisbursementListId { get; set; }
        public Nullable<System.DateTime> RetriveDate { get; set; }
        public Nullable<System.DateTime> DisbursementDate { get; set; }
        public string DepartmentId { get; set; }
        public string SignatureURL { get; set; }
        public string Status { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<DisbursementListDetail> DisbursementListDetails { get; set; }
    }
}
