//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Departments = new HashSet<Department>();
            this.Departments1 = new HashSet<Department>();
            this.Departments2 = new HashSet<Department>();
            this.PurchasingOrders = new HashSet<PurchasingOrder>();
            this.Requisitions = new HashSet<Requisition>();
            this.Logins = new HashSet<Login>();
            this.AdjustmentVouchers = new HashSet<AdjustmentVoucher>();
        }
    
        public int EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string Email { get; set; }
        public string DepartmentId { get; set; }
        public int RoleId { get; set; }
        public bool IsDelegate { get; set; }
    
        public virtual ICollection<Department> Departments { get; set; }
        public virtual ICollection<Department> Departments1 { get; set; }
        public virtual ICollection<Department> Departments2 { get; set; }
        public virtual Department Department { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<PurchasingOrder> PurchasingOrders { get; set; }
        public virtual ICollection<Requisition> Requisitions { get; set; }
        public virtual ICollection<Login> Logins { get; set; }
        public virtual ICollection<AdjustmentVoucher> AdjustmentVouchers { get; set; }
    }
}
