//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasingOrderDetail
    {
        public int PODetailId { get; set; }
        public int POId { get; set; }
        public string StationeryId { get; set; }
        public int OrderQty { get; set; }
        public int ReceivedQty { get; set; }
        public string Remarks { get; set; }
    
        public virtual PurchasingOrder PurchasingOrder { get; set; }
        public virtual Stationery Stationery { get; set; }
    }
}
