//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminder
    {
        public int ReminderId { get; set; }
        public string StationeryId { get; set; }
        public int Qty { get; set; }
        public bool Status { get; set; }
        public string Reason { get; set; }
        public string ReminderType { get; set; }
    
        public virtual Stationery Stationery { get; set; }
    }
}
