//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisition
    {
        public Requisition()
        {
            this.RequisitionDetails = new HashSet<RequisitionDetail>();
        }
    
        public int RequisitionId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string Status { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<RequisitionDetail> RequisitionDetails { get; set; }
    }
}
