//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetrievalList
    {
        public string Bin { get; set; }
        public string Description { get; set; }
        public string DepartmentName { get; set; }
        public int RequestQty { get; set; }
        public Nullable<int> GivenQty { get; set; }
        public Nullable<System.DateTime> RetriveDate { get; set; }
        public string Status { get; set; }
        public string StationeryId { get; set; }
        public int DisbursementListId { get; set; }
        public int BinStatus { get; set; }
    }
}
