//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdjustmentVoucherDetail> AdjustmentVoucherDetails { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<DisbursementList> DisbursementLists { get; set; }
        public DbSet<DisbursementListDetail> DisbursementListDetails { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<PurchasingOrder> PurchasingOrders { get; set; }
        public DbSet<PurchasingOrderDetail> PurchasingOrderDetails { get; set; }
        public DbSet<Requisition> Requisitions { get; set; }
        public DbSet<RequisitionDetail> RequisitionDetails { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<UOM> UOMs { get; set; }
        public DbSet<Reminder> Reminders { get; set; }
        public DbSet<StationeryTransaction> StationeryTransactions { get; set; }
        public DbSet<StorageBin> StorageBins { get; set; }
        public DbSet<Stationery> Stationeries { get; set; }
        public DbSet<Supplier> Suppliers { get; set; }
        public DbSet<RetrievalList> RetrievalLists { get; set; }
        public DbSet<Login> Logins { get; set; }
        public DbSet<AdjustmentVoucher> AdjustmentVouchers { get; set; }
        public DbSet<CollectionPoint> CollectionPoints { get; set; }
        public DbSet<Report> Reports { get; set; }
    
        public virtual ObjectResult<GetRetrievalListForBin_Result> GetRetrievalListForBin(string bin)
        {
            var binParameter = bin != null ?
                new ObjectParameter("Bin", bin) :
                new ObjectParameter("Bin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRetrievalListForBin_Result>("GetRetrievalListForBin", binParameter);
        }
    }
}
