//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationeryTransaction
    {
        public int StationeryTransactionID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Participant { get; set; }
        public string StationeryID { get; set; }
        public Nullable<int> TransactionQuantity { get; set; }
        public Nullable<int> Balance { get; set; }
    
        public virtual Stationery Stationery { get; set; }
    }
}
