//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.PurchasingOrders = new HashSet<PurchasingOrder>();
            this.Stationeries = new HashSet<Stationery>();
            this.Stationeries1 = new HashSet<Stationery>();
            this.Stationeries2 = new HashSet<Stationery>();
        }
    
        public string SupplierId { get; set; }
        public string SupplierName { get; set; }
        public string ContactName { get; set; }
        public string GST_Registration_No { get; set; }
        public string Phone_No { get; set; }
        public string Fax_No { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<PurchasingOrder> PurchasingOrders { get; set; }
        public virtual ICollection<Stationery> Stationeries { get; set; }
        public virtual ICollection<Stationery> Stationeries1 { get; set; }
        public virtual ICollection<Stationery> Stationeries2 { get; set; }
    }
}
